apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sysdig-bridge-logs
  namespace: sysdig-datadog-bridge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
